# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import requests
import math
from scipy import stats
import xlsxwriter
import yfinance as yf

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
stocks

    Ticker
0        A
1      AAL
2      AAP
3     AAPL
4     ABBV
..     ...
500    YUM
501    ZBH
502   ZBRA
503   ZION
504    ZTS

[505 rows x 1 columns]

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [10]:
tickers = stocks["Ticker"].dropna().tolist()
tickers = [ticker.strip() for ticker in tickers]


price_data = yf.download(
    tickers,
    period="2y",
    interval="1d",
    auto_adjust=True,
    group_by="ticker",
    threads=True,
    progress=False
)

price_data

data = []

for ticker in tickers:
    try:
        prices = price_data[ticker]["Close"].dropna()
        one_year_return = (prices.iloc[-1] / prices.iloc[0]) - 1

        data.append ({
            "Ticker": ticker,
            "Start Price": prices.iloc[0],
            "End Price": prices.iloc[-1],
            "One-Year Return": one_year_return,
            "One-Year Return %": one_year_return * 100
        })
    
    except Exception as e:
        data.append({
            "Ticker": ticker,
            "Start Price": None,
            "End Price": None,
            "One-Year Return": None,
            "One-Year Return %": None
        })

returns_df  = pd.DataFrame(data)
# readable number
# Optional sortieren (beste Performance zuerst)
returns_df = returns_df.sort_values("One-Year Return %", ascending=False)

returns_df

$ALXN: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$TIF: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$COG: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$MMC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$BRK.B: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$CTL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$CERN: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$MRO: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$KSU: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$MXIM: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$HFC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$VIAC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$MYL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$ANSS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$ATVI: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$PBCT: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$FLT: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$DISH: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$PEAK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$PKI: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$IPG: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$TWTR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$WLTW: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$DRE: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$FRC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$PXD: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$FBHS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$WBA: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$BF.B: possibly delisted; no price data found  (period=2y)
$VAR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$NBL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$CXO: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$ABC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$NLOK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$HBI: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$CMA: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$JNPR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$ABMD: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$ETFC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$DISCA: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$BLL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$WRK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$GPS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$DFS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$ANTM: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$XLNX: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$RE: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$CTXS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$SIVB: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$FLIR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$DISCK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$HES: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$NLSN: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$K: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")

54 Failed downloads:
['ALXN', 'TIF', 'COG', 'MMC', 'BRK.B', 'CTL', 'CERN', 'MRO', 'KSU', 'MXIM', 'HFC', 'VIAC', 'MYL', 'ANSS', 'ATVI', 'PBCT', 'FLT', 'DISH', 'PEAK', 'PKI', 'IPG', 'TWTR', 'WLTW', 'DRE', 'FRC', 'PXD', 'FBHS', 'WBA', 'VAR', 'NBL', 'CXO', 'ABC', 'NLOK', 'HBI', 'CMA', 'JNPR', 'ABMD', 'ETFC', 'DISCA', 'BLL', 'WRK', 'GPS', 'DFS', 'ANTM', 'XLNX', 'RE', 'CTXS', 'SIVB', 'FLIR', 'DISCK', 'HES', 'NLSN', 'K']: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
['BF.B']: possibly delisted; no price data found  (period=2y)

    Ticker  Start Price   End Price  One-Year Return  One-Year Return %
422    STX    86.180679  731.934998         7.493029         749.302887
479    WDC    54.639435  441.989990         7.089212         708.921234
202    GLW    32.097492  160.009995         3.985124         398.512449
324     MU   119.293228  578.340027         3.848054         384.805413
441    TPR    37.902439  140.589996         2.709260         270.925987
..     ...          ...         ...              ...                ...
467   VIAC          NaN         NaN              NaN                NaN
478    WBA          NaN         NaN              NaN                NaN
484   WLTW          NaN         NaN              NaN                NaN
489    WRK          NaN         NaN              NaN                NaN
495   XLNX          NaN         NaN              NaN                NaN

[505 rows x 5 columns]

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [11]:
returns_df = returns_df[:50]
returns_df

    Ticker  Start Price    End Price  One-Year Return  One-Year Return %
422    STX    86.180679   731.934998         7.493029         749.302887
479    WDC    54.639435   441.989990         7.089212         708.921234
202    GLW    32.097492   160.009995         3.985124         398.512449
324     MU   119.293228   578.340027         3.848054         384.805413
441    TPR    37.902439   140.589996         2.709260         270.925987
50    AVGO   128.408066   411.769989         2.206730         220.672994
242   INTC    30.774776    96.669998         2.141209         214.120879
233    HWM    79.745659   239.625000         2.004866         200.486576
194    FTI    26.038755    74.470001         1.859968         185.996777
275     LB    22.931553    65.099998         1.838883         183.888312
288   LRCX    90.778862   256.864990         1.829568         182.956830
385    PWR   268.877258   748.309998         1.783091         178.309145
331    NEM    39.942009   108.760002         1.722948         172.294772
79     CAT   333.027557   874.849976         1.626960         162.695971
37    ANET    69.705002   173.389999         1.487483         148.748289
102    CMI   272.482544   656.700012         1.410063         141.006269
64      BK    55.007874   131.729996         1.394748         139.474801
266   KLAC   706.665833  1691.660034         1.393861         139.386136
481   WELL    93.193077   217.625000         1.335206         133.520565
256    JCI    61.744949   144.044998         1.332903         133.290333
263   KEYS   150.600006   351.309998         1.332736         133.273561
44     APH    61.402378   141.449997         1.303657         130.365666
205  GOOGL   166.722061   382.440002         1.293878         129.387761
152   EBAY    47.805397   109.084999         1.281855         128.185531
167    ETR    51.462086   116.199997         1.257973         125.797294
204   GOOG   168.447067   379.709991         1.254180         125.417989
66     BKR    30.850441    68.830002         1.231086         123.108648
487    WMT    58.679119   130.449997         1.223108         122.310762
397     RL   162.100235   355.894989         1.195524         119.552420
31     AMD   155.779999   340.660004         1.186802         118.680194
199   GILD    61.532402   132.539993         1.153987         115.398699
172   EXPE   114.841843   247.149994         1.152090         115.209011
92    CHRW    75.357544   160.979996         1.136216         113.621606
345   NVDA    92.088036   196.110001         1.129593         112.959262
210     GS   425.283356   902.580994         1.122305         112.230500
421    STT    70.599869   148.210007         1.099296         109.929578
75       C    59.688847   125.300003         1.099220         109.921971
318     MS    89.690109   187.884995         1.094824         109.482401
77     CAH    95.778290   198.184998         1.069206         106.920585
115   CSCO    44.707420    92.320000         1.064982         106.498158
486    WMB    36.348854    75.029999         1.064164         106.416408
340    NRG    75.613167   153.190002         1.025970         102.596993
343   NTRS    80.304131   160.940002         1.004131         100.413106
10     ADI   196.994888   393.549988         0.997768          99.776751
474    VTR    44.411781    87.949997         0.980330          98.033032
191   FOXA    31.886341    62.639999         0.964477          96.447749
313     MO    37.574749    73.800003         0.964085          96.408506
182   FFIV   168.580002   327.119995         0.940444          94.044366
190    FOX    29.346897    56.415001         0.922350          92.234977
201     GL    79.407196   152.320007         0.918214          91.821415

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [12]:
returns_df.reset_index(inplace = True)
returns_df

    index Ticker  Start Price    End Price  One-Year Return  One-Year Return %
0     422    STX    86.180679   731.934998         7.493029         749.302887
1     479    WDC    54.639435   441.989990         7.089212         708.921234
2     202    GLW    32.097492   160.009995         3.985124         398.512449
3     324     MU   119.293228   578.340027         3.848054         384.805413
4     441    TPR    37.902439   140.589996         2.709260         270.925987
5      50   AVGO   128.408066   411.769989         2.206730         220.672994
6     242   INTC    30.774776    96.669998         2.141209         214.120879
7     233    HWM    79.745659   239.625000         2.004866         200.486576
8     194    FTI    26.038755    74.470001         1.859968         185.996777
9     275     LB    22.931553    65.099998         1.838883         183.888312
10    288   LRCX    90.778862   256.864990         1.829568         182.956830
11    385    PWR   268.877258   748.309998         1.783091         178.309145
12    331    NEM    39.942009   108.760002         1.722948         172.294772
13     79    CAT   333.027557   874.849976         1.626960         162.695971
14     37   ANET    69.705002   173.389999         1.487483         148.748289
15    102    CMI   272.482544   656.700012         1.410063         141.006269
16     64     BK    55.007874   131.729996         1.394748         139.474801
17    266   KLAC   706.665833  1691.660034         1.393861         139.386136
18    481   WELL    93.193077   217.625000         1.335206         133.520565
19    256    JCI    61.744949   144.044998         1.332903         133.290333
20    263   KEYS   150.600006   351.309998         1.332736         133.273561
21     44    APH    61.402378   141.449997         1.303657         130.365666
22    205  GOOGL   166.722061   382.440002         1.293878         129.387761
23    152   EBAY    47.805397   109.084999         1.281855         128.185531
24    167    ETR    51.462086   116.199997         1.257973         125.797294
25    204   GOOG   168.447067   379.709991         1.254180         125.417989
26     66    BKR    30.850441    68.830002         1.231086         123.108648
27    487    WMT    58.679119   130.449997         1.223108         122.310762
28    397     RL   162.100235   355.894989         1.195524         119.552420
29     31    AMD   155.779999   340.660004         1.186802         118.680194
30    199   GILD    61.532402   132.539993         1.153987         115.398699
31    172   EXPE   114.841843   247.149994         1.152090         115.209011
32     92   CHRW    75.357544   160.979996         1.136216         113.621606
33    345   NVDA    92.088036   196.110001         1.129593         112.959262
34    210     GS   425.283356   902.580994         1.122305         112.230500
35    421    STT    70.599869   148.210007         1.099296         109.929578
36     75      C    59.688847   125.300003         1.099220         109.921971
37    318     MS    89.690109   187.884995         1.094824         109.482401
38     77    CAH    95.778290   198.184998         1.069206         106.920585
39    115   CSCO    44.707420    92.320000         1.064982         106.498158
40    486    WMB    36.348854    75.029999         1.064164         106.416408
41    340    NRG    75.613167   153.190002         1.025970         102.596993
42    343   NTRS    80.304131   160.940002         1.004131         100.413106
43     10    ADI   196.994888   393.549988         0.997768          99.776751
44    474    VTR    44.411781    87.949997         0.980330          98.033032
45    191   FOXA    31.886341    62.639999         0.964477          96.447749
46    313     MO    37.574749    73.800003         0.964085          96.408506
47    182   FFIV   168.580002   327.119995         0.940444          94.044366
48    190    FOX    29.346897    56.415001         0.922350          92.234977
49    201     GL    79.407196   152.320007         0.918214          91.821415

In [13]:
# investment
portfolio_size = 1000000
# Price as numeric
returns_df["End Price"] = pd.to_numeric(returns_df["End Price"], errors="coerce")
# clean invalid values
returns_df = returns_df.replace([np.inf, -np.inf], np.nan)

# how many of each stock of the index is bought based on the portfolio size (investment)
position_size = portfolio_size / len(returns_df.index)
print(position_size)
returns_df["Number of Shares to Buy"] = np.where(
    returns_df["End Price"] > 0,
    np.floor(position_size / returns_df["End Price"]),
    np.nan
)

returns_df

20000.0

C:\Users\nadir_i69tsxn\AppData\Local\Temp\ipykernel_1600\2044626268.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  returns_df["End Price"] = pd.to_numeric(returns_df["End Price"], errors="coerce")

,index,Ticker,Start Price,End Price,One-Year Return,One-Year Return %,Number of Shares to Buy
0,422,STX,86.180679,731.934998,7.493029,749.302887,27.0
1,479,WDC,54.639435,441.989990,7.089212,708.921234,45.0
2,202,GLW,32.097492,160.009995,3.985124,398.512449,124.0
3,324,MU,119.293228,578.340027,3.848054,384.805413,34.0
4,441,TPR,37.902439,140.589996,2.709260,270.925987,142.0
5,50,AVGO,128.408066,411.769989,2.206730,220.672994,48.0
6,242,INTC,30.774776,96.669998,2.141209,214.120879,206.0
7,233,HWM,79.745659,239.625000,2.004866,200.486576,83.0
8,194,FTI,26.038755,74.470001,1.859968,185.996777,268.0
9,275,LB,22.931553,65.099998,1.838883,183.888312,307.0
10,288,LRCX,90.778862,256.864990,1.829568,182.956830,77.0
11,385,PWR,268.877258,748.309998,1.783091,178.309145,26.0
12,331,NEM,39.942009,108.760002,1.722948,172.294772,183.0
13,79,CAT,333.027557,874.849976,1.626960,162.695971,22.0
14,37,ANET,69.705002,173.389999,1.487483,148.748289,115.0
15,102,CMI,272.482544,656.700012,1.410063,141.006269,30.0
16,64,BK,55.007874,131.729996,1.394748,139.474801,151.0
17,266,KLAC,706.665833,1691.660034,1.393861,139.386136,11.0
18,481,WELL,93.193077,217.625000,1.335206,133.520565,91.0
19,256,JCI,61.744949,144.044998,1.332903,133.290333,138.0
20,263,KEYS,150.600006,351.309998,1.332736,133.273561,56.0
21,44,APH,61.402378,141.449997,1.303657,130.365666,141.0
22,205,GOOGL,166.722061,382.440002,1.293878,129.387761,52.0
23,152,EBAY,47.805397,109.084999,1.281855,128.185531,183.0
24,167,ETR,51.462086,116.199997,1.257973,125.797294,172.0
25,204,GOOG,168.447067,379.709991,1.254180,125.417989,52.0
26,66,BKR,30.850441,68.830002,1.231086,123.108648,290.0
27,487,WMT,58.679119,130.449997,1.223108,122.310762,153.0
28,397,RL,162.100235,355.894989,1.195524,119.552420,56.0
29,31,AMD,155.779999,340.660004,1.186802,118.680194,58.0
30,199,GILD,61.532402,132.539993,1.153987,115.398699,150.0
31,172,EXPE,114.841843,247.149994,1.152090,115.209011,80.0
32,92,CHRW,75.357544,160.979996,1.136216,113.621606,124.0
33,345,NVDA,92.088036,196.110001,1.129593,112.959262,101.0
34,210,GS,425.283356,902.580994,1.122305,112.230500,22.0
35,421,STT,70.599869,148.210007,1.099296,109.929578,134.0
36,75,C,59.688847,125.300003,1.099220,109.921971,159.0
37,318,MS,89.690109,187.884995,1.094824,109.482401,106.0
38,77,CAH,95.778290,198.184998,1.069206,106.920585,100.0
39,115,CSCO,44.707420,92.320000,1.064982,106.498158,216.0
40,486,WMB,36.348854,75.029999,1.064164,106.416408,266.0
41,340,NRG,75.613167,153.190002,1.025970,102.596993,130.0
42,343,NTRS,80.304131,160.940002,1.004131,100.413106,124.0
43,10,ADI,196.994888,393.549988,0.997768,99.776751,50.0
44,474,VTR,44.411781,87.949997,0.980330,98.033032,227.0
45,191,FOXA,31.886341,62.639999,0.964477,96.447749,319.0
46,313,MO,37.574749,73.800003,0.964085,96.408506,271.0
47,182,FFIV,168.580002,327.119995,0.940444,94.044366,61.0
48,190,FOX,29.346897,56.415001,0.922350,92.234977,354.0
49,201,GL,79.407196,152.320007,0.918214,91.821415,131.0

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [15]:
from scipy.stats import percentileofscore

portfolio_size = 1000000


def calculate_return(prices, months):
    prices = prices.dropna()

    if prices.empty:
        return np.nan

    end_date = prices.index[-1]
    start_date = end_date - pd.DateOffset(months=months)

    past_prices = prices[prices.index <= start_date]

    if past_prices.empty:
        return np.nan

    start_price = past_prices.iloc[-1]
    end_price = prices.iloc[-1]

    if start_price == 0:
        return np.nan

    return (end_price / start_price) - 1

rows = []

for ticker in tickers:
    try:
        prices = price_data[ticker]["Close"].dropna()

        rows.append({
            "Ticker": ticker,
            "Price": float(prices.iloc[-1]),
            "Number of Shares To Buy": 0,
            "One-Year Price Return": float(calculate_return(prices, 12)),
            "One-Year Return Percentile": np.nan,
            "Six-Month Price Return": float(calculate_return(prices, 6)),
            "Six-Month Return Percentile": np.nan,
            "Three-Month Price Return": float(calculate_return(prices, 3)),
            "Three-Month Return Percentile": np.nan,
            "One-Month Price Return": float(calculate_return(prices, 1)),
            "One-Month Return Percentile": np.nan
        })
    
    except Exception as e:
        print(ticker, e)
        continue

final_df = pd.DataFrame(rows)

percentile_columns = [
    "One-Year Return Percentile",
    "Six-Month Return Percentile",
    "Three-Month Return Percentile",
    "One-Month Return Percentile"
]

final_df[percentile_columns] = final_df[percentile_columns].astype(float)

for period in [
    "One-Year Price Return",
    "Six-Month Price Return",
    "Three-Month Price Return",
    "One-Month Price Return"
]:
    percentile_col = period.replace("Price Return", "Return Percentile")

    final_df[percentile_col] = final_df[period].apply(
        lambda x: percentileofscore(
            final_df[period].dropna(),
            x
        ) / 100 if pd.notna(x) else np.nan
    )

position_size = portfolio_size / len(final_df.index)

final_df["Number of Shares To Buy"] = np.floor(
    position_size / final_df["Price"]
).astype("Int64")

final_df.sort_values(
    "One-Year Return Percentile",
    ascending=False,
    inplace=True
)

final_df

ABC single positional indexer is out-of-bounds
ABMD single positional indexer is out-of-bounds
ALXN single positional indexer is out-of-bounds
ANSS single positional indexer is out-of-bounds
ANTM single positional indexer is out-of-bounds
ATVI single positional indexer is out-of-bounds
BF.B single positional indexer is out-of-bounds
BLL single positional indexer is out-of-bounds
BRK.B single positional indexer is out-of-bounds
CERN single positional indexer is out-of-bounds
CMA single positional indexer is out-of-bounds
COG single positional indexer is out-of-bounds
CTL single positional indexer is out-of-bounds
CTXS single positional indexer is out-of-bounds
CXO single positional indexer is out-of-bounds
DFS single positional indexer is out-of-bounds
DISCA single positional indexer is out-of-bounds
DISCK single positional indexer is out-of-bounds
DISH single positional indexer is out-of-bounds
DRE single positional indexer is out-of-bounds
ETFC single positional indexer is out-of-bounds
FBHS single positional indexer is out-of-bounds
FLIR single positional indexer is out-of-bounds
FLT single positional indexer is out-of-bounds
FRC single positional indexer is out-of-bounds
GPS single positional indexer is out-of-bounds
HBI single positional indexer is out-of-bounds
HES single positional indexer is out-of-bounds
HFC single positional indexer is out-of-bounds
IPG single positional indexer is out-of-bounds
JNPR single positional indexer is out-of-bounds
K single positional indexer is out-of-bounds
KSU single positional indexer is out-of-bounds
MMC single positional indexer is out-of-bounds
MRO single positional indexer is out-of-bounds
MXIM single positional indexer is out-of-bounds
MYL single positional indexer is out-of-bounds
NBL single positional indexer is out-of-bounds
NLOK single positional indexer is out-of-bounds
NLSN single positional indexer is out-of-bounds
PBCT single positional indexer is out-of-bounds
PEAK single positional indexer is out-of-bounds
PKI single positional indexer is out-of-bounds
PXD single positional indexer is out-of-bounds
RE single positional indexer is out-of-bounds
SIVB single positional indexer is out-of-bounds
TIF single positional indexer is out-of-bounds
TWTR single positional indexer is out-of-bounds
VAR single positional indexer is out-of-bounds
VIAC single positional indexer is out-of-bounds
WBA single positional indexer is out-of-bounds
WLTW single positional indexer is out-of-bounds
WRK single positional indexer is out-of-bounds
XLNX single positional indexer is out-of-bounds

,Ticker,Price,Number of Shares To Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile
428,WDC,441.989990,5,8.932823,1.000000,1.908116,0.997783,0.641370,0.993348,0.498424,0.986696
376,STX,731.934998,3,6.965709,0.997778,1.936079,1.000000,0.751455,0.997783,0.704712,0.995565
289,MU,578.340027,3,6.181917,0.995556,1.654757,0.995565,0.524995,0.986696,0.579129,0.993348
213,INTC,96.669998,22,3.688167,0.993333,1.610586,0.993348,0.989095,1.000000,0.918817,0.997783
177,GLW,160.009995,13,2.549429,0.991111,0.887754,0.984479,0.461470,0.982262,0.081733,0.778271
...,...,...,...,...,...,...,...,...,...,...,...
83,CHTR,171.705002,12,-0.554013,0.008889,-0.222738,0.082040,-0.234075,0.055432,-0.218777,0.004435
165,FMC,14.650000,151,-0.595766,0.006667,0.104010,0.574279,-0.133605,0.206208,-0.174648,0.008869
162,FISV,63.029999,35,-0.658133,0.004444,-0.022033,0.314856,0.055425,0.694013,0.122329,0.869180
221,IT,145.384995,15,-0.659910,0.002222,-0.360017,0.013304,-0.078851,0.339246,-0.078967,0.090909
156,FB,43.776199,50,NaN,NaN,0.054366,0.472284,0.042489,0.654102,0.032165,0.567627

In [16]:
final_df

,Ticker,Price,Number of Shares To Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile
428,WDC,441.989990,5,8.932823,1.000000,1.908116,0.997783,0.641370,0.993348,0.498424,0.986696
376,STX,731.934998,3,6.965709,0.997778,1.936079,1.000000,0.751455,0.997783,0.704712,0.995565
289,MU,578.340027,3,6.181917,0.995556,1.654757,0.995565,0.524995,0.986696,0.579129,0.993348
213,INTC,96.669998,22,3.688167,0.993333,1.610586,0.993348,0.989095,1.000000,0.918817,0.997783
177,GLW,160.009995,13,2.549429,0.991111,0.887754,0.984479,0.461470,0.982262,0.081733,0.778271
...,...,...,...,...,...,...,...,...,...,...,...
83,CHTR,171.705002,12,-0.554013,0.008889,-0.222738,0.082040,-0.234075,0.055432,-0.218777,0.004435
165,FMC,14.650000,151,-0.595766,0.006667,0.104010,0.574279,-0.133605,0.206208,-0.174648,0.008869
162,FISV,63.029999,35,-0.658133,0.004444,-0.022033,0.314856,0.055425,0.694013,0.122329,0.869180
221,IT,145.384995,15,-0.659910,0.002222,-0.360017,0.013304,-0.078851,0.339246,-0.078967,0.090909
156,FB,43.776199,50,NaN,NaN,0.054366,0.472284,0.042489,0.654102,0.032165,0.567627

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [18]:
from statistics import mean

for row in final_df.index:
    momentum_percentiles = [
        final_df.loc[row, "One-Year Return Percentile"],
        final_df.loc[row, "Six-Month Return Percentile"],
        final_df.loc[row, "Three-Month Return Percentile"],
        final_df.loc[row, "One-Month Return Percentile"]
    ]
    
    final_df.loc[row, "HQM Score"] = mean(momentum_percentiles)

final_df.sort_values(
    "HQM Score",
    ascending=False,
    inplace=True
)

hqm_dataframe = final_df[:50]
hqm_dataframe.reset_index(drop=True, inplace=True)
position_size = portfolio_size / len(hqm_dataframe.index)

hqm_dataframe["Number of Shares To Buy"] = np.floor(
    position_size / hqm_dataframe["Price"]
).astype("Int64")

hqm_dataframe

C:\Users\nadir_i69tsxn\AppData\Local\Temp\ipykernel_1600\4251704793.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hqm_dataframe["Number of Shares To Buy"] = np.floor(

,Ticker,Price,Number of Shares To Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,STX,731.934998,27,6.965709,0.997778,1.936079,1.000000,0.751455,0.997783,0.704712,0.995565,0.997781
1,INTC,96.669998,206,3.688167,0.993333,1.610586,0.993348,0.989095,1.000000,0.918817,0.997783,0.996116
2,WDC,441.989990,45,8.932823,1.000000,1.908116,0.997783,0.641370,0.993348,0.498424,0.986696,0.994457
3,MU,578.340027,34,6.181917,0.995556,1.654757,0.995565,0.524995,0.986696,0.579129,0.993348,0.992791
4,PWR,748.309998,26,1.332412,0.966667,0.706680,0.968958,0.611075,0.991131,0.334766,0.975610,0.975591
5,KEYS,351.309998,56,1.365405,0.971111,0.961530,0.988914,0.585334,0.988914,0.206256,0.933481,0.970605
6,AMD,340.660004,58,2.447976,0.986667,0.362368,0.886918,0.701683,0.995565,0.566253,0.991131,0.965070
7,CAT,874.849976,22,1.732076,0.982222,0.604453,0.960089,0.266970,0.933481,0.222101,0.937916,0.953427
8,MCHP,94.830002,210,1.038528,0.953333,0.617626,0.962306,0.219332,0.904656,0.445579,0.984479,0.951194
9,TXN,280.885010,71,0.746420,0.913333,0.774086,0.973392,0.260026,0.931264,0.441397,0.982262,0.950063
10,LRCX,256.864990,77,2.472183,0.988889,0.653589,0.964523,0.225916,0.911308,0.175906,0.917960,0.945670
11,ADI,393.549988,50,1.011956,0.948889,0.727163,0.971175,0.232001,0.913525,0.236257,0.942350,0.943985
12,AMAT,389.940002,51,1.536611,0.977778,0.699429,0.966741,0.311916,0.960089,0.119006,0.860310,0.941229
13,GLW,160.009995,124,2.549429,0.991111,0.887754,0.984479,0.461470,0.982262,0.081733,0.778271,0.934031
14,NUE,223.884995,89,0.848259,0.931111,0.562233,0.951220,0.182672,0.886918,0.298185,0.964523,0.933443
15,KLAC,1691.660034,11,1.441398,0.973333,0.421629,0.917960,0.295771,0.953437,0.115253,0.855876,0.925152
16,GOOGL,382.440002,52,1.339609,0.968889,0.379835,0.902439,0.149139,0.858093,0.293032,0.962306,0.922932
17,GOOG,379.709991,52,1.297948,0.964444,0.367422,0.893570,0.139910,0.842572,0.289513,0.960089,0.915169
18,BKR,68.830002,290,0.892837,0.935556,0.502929,0.935698,0.167647,0.873614,0.139947,0.893570,0.909610
19,HAL,41.685001,479,1.079021,0.955556,0.572296,0.953437,0.219771,0.906874,0.092088,0.809313,0.906295
20,AVGO,411.769989,48,1.038432,0.951111,0.174698,0.720621,0.339503,0.966741,0.309076,0.966741,0.901303
21,CMI,656.700012,30,1.230818,0.962222,0.543483,0.944568,0.087971,0.762749,0.194695,0.931264,0.900201
22,EBAY,109.084999,183,0.612553,0.868889,0.344709,0.875831,0.275043,0.942350,0.158753,0.900222,0.896823
23,FANG,212.929993,93,0.598864,0.860000,0.546968,0.949002,0.267547,0.937916,0.098257,0.831486,0.894601
24,FTI,74.470001,268,1.522495,0.975556,0.782508,0.975610,0.318155,0.962306,0.048578,0.643016,0.889122
25,CBOE,338.885010,59,0.504776,0.831111,0.357476,0.882483,0.252662,0.929047,0.168770,0.913525,0.889042
26,SLB,56.160000,356,0.666475,0.891111,0.576342,0.955654,0.100120,0.796009,0.135922,0.889135,0.882977
27,HPE,28.700001,696,0.745318,0.911111,0.233395,0.782705,0.242903,0.924612,0.166193,0.906874,0.881325
28,CE,68.910004,290,0.503033,0.828889,0.847385,0.980044,0.306218,0.957871,0.076207,0.758315,0.881280
29,ALB,190.220001,105,2.209937,0.984444,1.162428,0.991131,0.130625,0.829268,0.068112,0.707317,0.878040
30,ANET,173.389999,115,0.904966,0.937778,0.129209,0.629712,0.330903,0.964523,0.368724,0.977827,0.877460
31,IPGP,122.019997,163,0.912539,0.940000,0.452619,0.926829,0.221544,0.909091,0.070914,0.722838,0.874690
32,IRM,127.489998,156,0.378012,0.757778,0.257024,0.804878,0.426995,0.980044,0.234172,0.940133,0.870708
33,STT,148.210007,134,0.683004,0.895556,0.292967,0.842572,0.130048,0.824834,0.150699,0.895787,0.864687
34,CSCO,92.320000,216,0.591858,0.855556,0.290334,0.840355,0.143670,0.851441,0.168312,0.911308,0.864665
35,VLO,251.255005,79,1.174731,0.960000,0.504262,0.937916,0.280541,0.944568,0.029354,0.563193,0.851419
36,MPC,251.949997,79,0.818114,0.926667,0.384740,0.906874,0.292429,0.951220,0.042279,0.618625,0.850846
37,BEN,29.405001,680,0.549735,0.846667,0.338828,0.866962,0.072035,0.729490,0.256624,0.953437,0.849139
38,JBHT,239.645004,83,0.813911,0.924444,0.394529,0.911308,0.052163,0.676275,0.115095,0.851441,0.840867
39,CSX,45.220001,442,0.599601,0.862222,0.270553,0.811530,0.138493,0.838137,0.097040,0.829268,0.835289
40,NTRS,160.940002,124,0.691904,0.900000,0.276620,0.824834,0.073225,0.731707,0.131388,0.878049,0.833647
41,DVN,51.299999,389,0.673937,0.893333,0.594468,0.957871,0.188475,0.893570,0.036573,0.585366,0.832535
42,JCI,144.044998,138,0.630834,0.880000,0.301234,0.851441,0.115832,0.811530,0.083289,0.784922,0.831973
43,AAP,58.404999,342,0.782611,0.920000,0.227127,0.773836,0.076017,0.745011,0.131863,0.880266,0.829778
44,MO,73.800003,271,0.325144,0.720000,0.333273,0.862528,0.151575,0.862528,0.122263,0.866962,0.828004
45,HST,20.945000,954,0.495091,0.822222,0.344628,0.873614,0.096235,0.780488,0.094305,0.820399,0.824181
46,APA,41.220001,485,1.608542,0.980000,0.896356,0.986696,0.515555,0.984479,-0.012942,0.341463,0.823160
47,TGT,129.020004,155,0.385759,0.762222,0.466715,0.929047,0.141963,0.844789,0.071150,0.729490,0.816387
48,PVH,89.040001,224,0.270112,0.662222,0.187954,0.725055,0.357058,0.977827,0.154714,0.898004,0.815777
49,ETN,427.450012,46,0.443797,0.804444,0.138321,0.649667,0.174748,0.878049,0.183744,0.929047,0.815302

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

In [34]:
# initialize writer with engine
writer = pd.ExcelWriter('recommended_trades_momentum.xlsx', engine='xlsxwriter')
# Specify tabs
hqm_dataframe.to_excel(writer, 'Recommended Trades Momentum', index = False)

C:\Users\nadir_i69tsxn\AppData\Local\Temp\ipykernel_1600\557929491.py:4: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  hqm_dataframe.to_excel(writer, 'Recommended Trades Momentum', index = False)

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [35]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [36]:
column_formats = {
'A': ['Ticker', string_template],
'B': ['Price', dollar_template],
'C': ['Number of Shares To Buy', integer_template],
'D': ['One-Year Price Return', percent_template],
'E': ['One-Year Price Return Percentile', percent_template],
'F': ['Six-Month Price Return', percent_template],
'G': ['Six-Month Price Return Percentile', percent_template],
'H': ['Three-Month Price Return Percentile', percent_template],
'I': ['Three-Month Price Return Percentile', percent_template],
'J': ['One-Month Price Return Percentile', percent_template],
'K': ['One-Month Price Return Percentile', percent_template],
'L': ['HQM Score', percent_template],
}

for column in column_formats.keys():
    writer.sheets['Recommended Trades Momentum'].set_column(f'{column}:{column}', 22, column_formats[column][1])
    writer.sheets['Recommended Trades Momentum'].write(f'{column}1', column_formats[column][0], column_formats[column][1])

writer.close()

## Saving Our Excel Output

As before, saving our Excel output is very easy: